" Source whatever system settings there are
source /etc/vimrc

" Show line numbers
set number

" Set default window size
set lines=40

" Set default font
set guifont=Monospace\ 13

" Set default colorscheme
colorscheme distinguished

" Set up tabbing
set smartindent
set tabstop=3
set softtabstop=3
set shiftwidth=3
set expandtab

" Set up copy, cut, and paste with ctrl-c, ctrl-x, ctrl-v respectively
"nmap <C-V> "+gP
imap <C-V> <ESC><C-V>i
vmap <C-C> "+y
vmap <C-x> "+x

filetype plugin indent on
syntax on

au BufRead * let &numberwidth = float2nr(log10(line("$"))) + 2
          \| let &columns = &numberwidth + 80
