#!/bin/bash

#xmodmap -e "keycode 118 = Home"
#xmodmap -e "keycode 110 = End"
#xmodmap -e "keycode 115 = Insert"
xmodmap -e "keycode 77 = BackSpace"
xmodmap -e "keycode 90 = KP_0"
xmodmap -e "keycode 87 = KP_1"
xmodmap -e "keycode 88 = KP_2"
xmodmap -e "keycode 89 = KP_3"
xmodmap -e "keycode 83 = KP_4"
xmodmap -e "keycode 84 = KP_5"
xmodmap -e "keycode 85 = KP_6"
xmodmap -e "keycode 79 = KP_7"
xmodmap -e "keycode 80 = KP_8"
xmodmap -e "keycode 81 = KP_9"
xmodmap -e "keycode 91 = KP_Decimal"
