#!/bin/bash

alias g="gvim -p"
#alias sudo="sudo "
alias ls='ls --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias ll='ls -lh --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias la='ls -lha --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias grep='grep --color=tty -d skip'
alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano PKGBUILD'
alias psg='ps -ef | grep -i'
alias cd.='cd ..'
alias cd..='cd ../..'
alias cd...='cd ../../..'
alias cd....='cd ../../../..'
alias cd.....='cd ../../../../..'
alias path='echo $PATH | tr ":" "\n"'
alias ldpath='echo $LD_LIBRARY_PATH | tr ":" "\n"'
alias pypath='echo $PYTHONPATH | tr ":" "\n"'
alias ssh='ssh -X'
alias todo=task

function gvim ()
{
   (/usr/bin/gvim -f "$@" &)
}

# extract - archive extractor
# usage: extract <file>
function extract()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via extract()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

function colors() {
	local fgc bgc vals seq0

	printf "Color escapes are %s\n" '\e[${value};...;${value}m'
	printf "Values 30..37 are \e[33mforeground colors\e[m\n"
	printf "Values 40..47 are \e[43mbackground colors\e[m\n"
	printf "Value  1 gives a  \e[1mbold-faced look\e[m\n\n"

	# foreground colors
	for fgc in {30..37}; do
		# background colors
		for bgc in {40..47}; do
			fgc=${fgc#37} # white
			bgc=${bgc#40} # black

			vals="${fgc:+$fgc;}${bgc}"
			vals=${vals%%;}

			seq0="${vals:+\e[${vals}m}"
			printf "  %-9s" "${seq0:-(default)}"
			printf " ${seq0}TEXT\e[m"
			printf " \e[${vals:+${vals+$vals;}}1mBOLD\e[m\n"
		done
		echo; echo
	done
}

alias psg &> /dev/null && unalias psg
function psg()
{
    ps -ef | grep -i "$1" | grep -v "grep"
}

function getWorkspace()
{
    if which xprop 2>&1 > /dev/null; then
        xprop -root -notype _NET_CURRENT_DESKTOP | cut -d" " -f 3
    elif [[ "$DESKTOP_SESSION" == "kde" ]]; then
        qdbus org.kde.kwin /kWin currentDesktop
    elif [[ "$DESKTOP_SESSION" == "gnome" ]]; then
        xprop -root -notype _NET_CURRENT_DESKTOP | sed -re 's/^.*= ([0-9]+)/\1/'
    else
        echo "unknown"
    fi
}

function calc()
{
    bc -l <<<"scale=10; $1"
}

function parse_git_branch()
{
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

function colors2()
{
    for x in {0..8}; do
        for i in {30..37}; do
            for a in {40..47}; do
                echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "
            done
            echo
        done
    done
}
